### ISSUE TITLE
Contact request

### ISSUE THREAD

**Issue by adouge** [ChristopherMayes/lume-astra#1]
Hi!

Me and a classmate of mine are working on solenoid magnet simulation and tracking-based characterization for our bachelor theses at Helmholtz Center Berlin 

After you added a second repo on Python/Superfish interaction, I started wondering whether we're working on similar things.

Would you be interested in some exchange? I tried googling your project (LUME), but nothing turned up. Could you perhaps give me a link with some description?

I am particularly interested in your python Astra Interface; it appears to be a more complex piece pf software than my needs would require, but, if you don't mind, I would like to learn about the concepts and principles you have used in the design, to compare with my ideas for our implementation of a small astra wrapper, as well as poisson/superfish integration.

I'll start:

our "theses" are pretty much targeted at developing a solenoid-with-yoke electromagnet lens for a particular machine, via optimizing the design and later "checking" its performance with tracking methods, pre-production. We want to invest some extra time to produce, later on, a comprehensive software package that would automatize and flexibly implememt all the design stages/elements (field calculation, analytic and tracking-based characterization of the resulting field and its effects on the beam, geometry optimization constrained by target requirements, visualization) in an iPython/script-based environment.

Looking forward to your reply!

-Anton

**Comment by adouge** [comment]
And, would you mind if we were (not sure yet) to use your code as dependency / directly, also the pySuperfish? With all due credit, of course.

**Comment by ChristopherMayes** [comment]
@adouge Hi Anton, I apologize, I just now see this message. I will email you.

**Comment by hayg25** [comment]
dear All, 
we face some issues on windows machine. 
Astra runs and ends up with an error message
```
Press return to continue...
Run Aborted Command '['D:\\dcgun\\Astra.exe', 'D:/dcgun/astra.in']' returned non-zero exit status 24.
{'start_time': 1616163965.262801, 'run_script': 'D:\\dcgun\\Astra.exe D:/dcgun/astra.in', 'why_error': "Command '['D:\\\\dcgun\\\\Astra.exe', 'D:/dcgun/astra.in']' returned non-zero exit status 24.", 'run_time': 10.550769329071045, 'run_error': True}
```
under linux ou Mac we face no particular problem. 

Thanks for the help
