### ISSUE TITLE
Error message on windows 

### ISSUE THREAD

**Issue by hayg25** [ChristopherMayes/lume-astra#2]
dear All,
we face some issues on windows machine.
Astra runs and ends up with an error message
```
Press return to continue...
Run Aborted Command '['D:\\dcgun\\Astra.exe', 'D:/dcgun/astra.in']' returned non-zero exit status 24.
{'start_time': 1616163965.262801, 'run_script': 'D:\\dcgun\\Astra.exe D:/dcgun/astra.in', 'why_error': "Command '['D:\\\\dcgun\\\\Astra.exe', 'D:/dcgun/astra.in']' returned non-zero exit status 24.", 'run_time': 10.550769329071045, 'run_error': True}
```
under linux ou Mac we face no particular problem.

Thanks for the help

**Comment by hhslepicka** [comment]
@hayg25 I was able to reproduce the issue locally using a Windows Virtual Machine and the example files. We will investigate the issue.
