### ISSUE TITLE
Error message on windows

### ISSUE THREAD

**Issue by polarcos** [ChristopherMayes/lume-astra#21]
Dear All,
I'm trying to run lume-astra using a astra.in file. I put the Astra file and astra.in file in the same path. But everytime I run `A.run` or `run_astra` function I get an error message:
```
AssertionError: ERROR: Command does not exist:c:\Users\Polar\Desktop\lume-astra\$ASTRA_BIN
```
I presume it has to do with the $ASTRA_BIN setting but I don't know how to set it.

Thanks for your help!

**Comment by ChristopherMayes** [comment]
You have to set environmental variables to point to your executables. See: https://christophermayes.github.io/lume-astra/examples/install_astra/

**Comment by polarcos** [comment]
I set an environment variable named ASTRA_BIN and pointed it to the executable file ASTRA and it worked!

Thanks a lot for your answer!
