### ISSUE TITLE
Error on Windows (2)

### ISSUE THREAD

**Issue by hayg25** [ChristopherMayes/lume-astra#4]
Dear All, 
thanks for the feedback, we are again facing an issue on Windows machine. See the error below 

```
Press return to continue...
Run Aborted Stat keys do not all have the same length: []
{'start_time': 1616683629.643803, 'run_script': 'D:\\dcgun\\Astra.exe astra.in', 'why_error': 'Stat keys do not all have the same length: []', 'run_time': 4.086401700973511, 'run_error': True}
```

thanks for your help,

**Comment by hhslepicka** [comment]
@hayg25 do you see this same error running the examples?

**Comment by hayg25** [comment]
@hhslepicka, not exactly :  
-> 'why_error': 'Stat keys do not all have the same length: []'
->  "Command '['D:\\\\dcgun\\\\Astra.exe', 'D:/dcgun/astra.in']' returned non-zero exit status 24."

**Comment by hayg25** [comment]
@hhslepicka, 
the error is seen on DCgun example. I guess the error is also there on the other examples. 
Thanks for your help.

**Comment by ChristopherMayes** [comment]
@hayg25 What version are you using? The latest on GitHub, and conda-forge, work for me in `simple_astra_run` notebook on Windows.

**Comment by hayg25** [comment]
Ok it seems to re related to the fact that we modified A.path  
Seems fine if we live it unchanged
